<?php
/**
 * Royita ACF Local Field Groups
 *
 * @package Royita
 */

defined('ABSPATH') || exit;

add_action('acf/init', 'royita_register_acf_fields');
function royita_register_acf_fields() {
    if (!function_exists('acf_add_local_field_group')) return;

    // =====================================================
    // CAMPAIGN FIELD GROUP
    // =====================================================
    acf_add_local_field_group([
        'key'      => 'group_campaign',
        'title'    => 'جزئیات کمپین',
        'fields'   => [
            [
                'key'     => 'field_campaign_status',
                'label'   => 'وضعیت کمپین',
                'name'    => 'campaign_status',
                'type'    => 'select',
                'choices' => [
                    'draft'     => 'پیش‌نویس',
                    'active'    => 'فعال',
                    'paused'    => 'متوقف',
                    'completed' => 'تکمیل شده',
                    'cancelled' => 'لغو شده',
                ],
                'default_value' => 'draft',
                'allow_null'    => 0,
                'return_format' => 'value',
            ],
            [
                'key'     => 'field_campaign_type',
                'label'   => 'نوع کمپین',
                'name'    => 'campaign_type',
                'type'    => 'select',
                'choices' => [
                    'product_video' => 'ویدیو محصول',
                    'reel'          => 'ریلز',
                    'youtube'       => 'یوتیوب',
                    'tvc'           => 'تبلیغ تلویزیونی',
                    'documentary'   => 'مستند',
                ],
                'allow_null'    => 0,
                'return_format' => 'value',
            ],
            [
                'key'     => 'field_campaign_platforms',
                'label'   => 'پلتفرم‌های هدف',
                'name'    => 'campaign_platforms',
                'type'    => 'checkbox',
                'choices' => [
                    'instagram' => 'اینستاگرام',
                    'youtube'   => 'یوتیوب',
                    'tiktok'    => 'تیک‌تاک',
                    'aparat'    => 'آپارات',
                ],
                'layout'        => 'horizontal',
                'return_format' => 'value',
            ],
            [
                'key'          => 'field_campaign_budget_min',
                'label'        => 'حداقل بودجه',
                'name'         => 'campaign_budget_min',
                'type'         => 'number',
                'prepend'      => 'تومان',
                'min'          => 0,
                'step'         => 1000,
            ],
            [
                'key'          => 'field_campaign_budget_max',
                'label'        => 'حداکثر بودجه',
                'name'         => 'campaign_budget_max',
                'type'         => 'number',
                'prepend'      => 'تومان',
                'min'          => 0,
                'step'         => 1000,
            ],
            [
                'key'            => 'field_campaign_deadline',
                'label'          => 'مهلت ارسال پیشنهاد',
                'name'           => 'campaign_deadline',
                'type'           => 'date_picker',
                'display_format' => 'Y/m/d',
                'return_format'  => 'Y/m/d',
                'first_day'      => 6,
            ],
            [
                'key'      => 'field_campaign_brief',
                'label'    => 'بریف کمپین',
                'name'     => 'campaign_brief',
                'type'     => 'textarea',
                'rows'     => 8,
                'new_lines'=> 'wpautop',
            ],
            [
                'key'        => 'field_campaign_requirements',
                'label'      => 'الزامات کمپین',
                'name'       => 'campaign_requirements',
                'type'       => 'repeater',
                'layout'     => 'block',
                'button_label' => 'افزودن الزام',
                'sub_fields' => [
                    [
                        'key'   => 'field_requirement_text',
                        'label' => 'توضیح الزام',
                        'name'  => 'requirement_text',
                        'type'  => 'text',
                    ],
                ],
            ],
            [
                'key'        => 'field_campaign_deliverables',
                'label'      => 'تحویلی‌ها',
                'name'       => 'campaign_deliverables',
                'type'       => 'repeater',
                'layout'     => 'table',
                'button_label' => 'افزودن تحویلی',
                'sub_fields' => [
                    [
                        'key'   => 'field_deliverable_text',
                        'label' => 'توضیح تحویلی',
                        'name'  => 'deliverable_text',
                        'type'  => 'text',
                    ],
                    [
                        'key'     => 'field_deliverable_format',
                        'label'   => 'فرمت فایل',
                        'name'    => 'deliverable_format',
                        'type'    => 'select',
                        'choices' => [
                            'mp4' => 'MP4',
                            'mov' => 'MOV',
                            'gif' => 'GIF',
                            'jpg' => 'JPG',
                        ],
                        'allow_null' => 0,
                    ],
                ],
            ],
            [
                'key'   => 'field_campaign_target_audience',
                'label' => 'مخاطب هدف',
                'name'  => 'campaign_target_audience',
                'type'  => 'text',
            ],
            [
                'key'        => 'field_campaign_reference_links',
                'label'      => 'لینک‌های مرجع',
                'name'       => 'campaign_reference_links',
                'type'       => 'repeater',
                'layout'     => 'table',
                'button_label' => 'افزودن لینک',
                'sub_fields' => [
                    [
                        'key'   => 'field_ref_url',
                        'label' => 'لینک',
                        'name'  => 'ref_url',
                        'type'  => 'url',
                    ],
                    [
                        'key'   => 'field_ref_note',
                        'label' => 'توضیح',
                        'name'  => 'ref_note',
                        'type'  => 'text',
                    ],
                ],
            ],
            [
                'key'           => 'field_campaign_brand_assets',
                'label'         => 'فایل‌های برند',
                'name'          => 'campaign_brand_assets',
                'type'          => 'file',
                'return_format' => 'array',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_is_featured',
                'label'         => 'کمپین ویژه',
                'name'          => 'is_featured',
                'type'          => 'true_false',
                'ui'            => 1,
                'ui_on_text'    => 'بله',
                'ui_off_text'   => 'خیر',
            ],
            [
                'key'      => 'field_proposals_count',
                'label'    => 'تعداد پیشنهادها',
                'name'     => 'proposals_count',
                'type'     => 'number',
                'readonly' => 1,
                'min'      => 0,
                'default_value' => 0,
            ],
        ],
        'location' => [
            [['param' => 'post_type', 'operator' => '==', 'value' => 'royita_campaign']],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'active'                => true,
    ]);

    // =====================================================
    // CREATOR FIELD GROUP
    // =====================================================
    acf_add_local_field_group([
        'key'    => 'group_creator',
        'title'  => 'پروفایل کریتور',
        'fields' => [
            [
                'key'     => 'field_creator_type',
                'label'   => 'نوع کریتور',
                'name'    => 'creator_type',
                'type'    => 'select',
                'choices' => [
                    'videographer'    => 'ویدیوگرافر',
                    'influencer'      => 'اینفلوئنسر',
                    'motion_designer' => 'موشن دیزاینر',
                    'animator'        => 'انیماتور',
                    'editor'          => 'تدوینگر',
                ],
                'allow_null' => 0,
            ],
            [
                'key'      => 'field_creator_bio',
                'label'    => 'بیوگرافی',
                'name'     => 'creator_bio',
                'type'     => 'textarea',
                'rows'     => 5,
                'new_lines'=> 'wpautop',
            ],
            [
                'key'     => 'field_creator_skills',
                'label'   => 'مهارت‌ها',
                'name'    => 'creator_skills',
                'type'    => 'checkbox',
                'choices' => [
                    'filming'       => 'فیلم‌برداری',
                    'editing'       => 'تدوین',
                    'color_grading' => 'رنگ‌بندی',
                    'animation'     => 'انیمیشن',
                    'motion'        => 'موشن گرافیک',
                    'storytelling'  => 'داستان‌سرایی',
                    'acting'        => 'بازیگری',
                    'voiceover'     => 'صداگذاری',
                ],
                'layout' => 'horizontal',
            ],
            [
                'key'   => 'field_creator_instagram_followers',
                'label' => 'فالوور اینستاگرام',
                'name'  => 'creator_instagram_followers',
                'type'  => 'number',
                'min'   => 0,
            ],
            [
                'key'   => 'field_creator_youtube_subscribers',
                'label' => 'مشترک یوتیوب',
                'name'  => 'creator_youtube_subscribers',
                'type'  => 'number',
                'min'   => 0,
            ],
            [
                'key'    => 'field_creator_rate_reel',
                'label'  => 'نرخ ریلز (تومان)',
                'name'   => 'creator_rate_reel',
                'type'   => 'number',
                'prepend'=> 'تومان',
                'min'    => 0,
            ],
            [
                'key'    => 'field_creator_rate_youtube',
                'label'  => 'نرخ ویدیو یوتیوب (تومان)',
                'name'   => 'creator_rate_youtube',
                'type'   => 'number',
                'prepend'=> 'تومان',
                'min'    => 0,
            ],
            [
                'key'        => 'field_creator_portfolio',
                'label'      => 'پورتفولیو',
                'name'       => 'creator_portfolio',
                'type'       => 'repeater',
                'layout'     => 'block',
                'button_label' => 'افزودن نمونه کار',
                'sub_fields' => [
                    [
                        'key'   => 'field_portfolio_title',
                        'label' => 'عنوان',
                        'name'  => 'portfolio_title',
                        'type'  => 'text',
                    ],
                    [
                        'key'   => 'field_portfolio_video_url',
                        'label' => 'لینک ویدیو',
                        'name'  => 'portfolio_video_url',
                        'type'  => 'url',
                    ],
                    [
                        'key'           => 'field_portfolio_thumbnail',
                        'label'         => 'تصویر بند انگشتی',
                        'name'          => 'portfolio_thumbnail',
                        'type'          => 'image',
                        'return_format' => 'array',
                        'preview_size'  => 'medium',
                    ],
                    [
                        'key'   => 'field_portfolio_brand',
                        'label' => 'نام برند',
                        'name'  => 'portfolio_brand',
                        'type'  => 'text',
                    ],
                    [
                        'key'   => 'field_portfolio_views',
                        'label' => 'تعداد بازدید',
                        'name'  => 'portfolio_views',
                        'type'  => 'number',
                        'min'   => 0,
                    ],
                ],
            ],
            [
                'key'  => 'field_creator_rating',
                'label'=> 'امتیاز',
                'name' => 'creator_rating',
                'type' => 'number',
                'step' => 0.1,
                'min'  => 0,
                'max'  => 5,
            ],
            [
                'key'  => 'field_creator_total_projects',
                'label'=> 'تعداد پروژه‌های تکمیل شده',
                'name' => 'creator_total_projects',
                'type' => 'number',
                'min'  => 0,
                'default_value' => 0,
            ],
            [
                'key'        => 'field_creator_verified',
                'label'      => 'تأیید شده',
                'name'       => 'creator_verified',
                'type'       => 'true_false',
                'ui'         => 1,
                'ui_on_text' => 'بله',
                'ui_off_text'=> 'خیر',
            ],
            [
                'key'     => 'field_creator_badge',
                'label'   => 'نشان کریتور',
                'name'    => 'creator_badge',
                'type'    => 'select',
                'choices' => [
                    'none'   => 'بدون نشان',
                    'rising' => 'در حال رشد',
                    'top'    => 'برتر',
                    'pro'    => 'حرفه‌ای',
                    'elite'  => 'الیت',
                ],
                'default_value' => 'none',
            ],
            [
                'key'     => 'field_creator_availability',
                'label'   => 'وضعیت دسترسی',
                'name'    => 'creator_availability',
                'type'    => 'select',
                'choices' => [
                    'available' => 'آزاد',
                    'busy'      => 'مشغول',
                    'vacation'  => 'تعطیل',
                ],
                'default_value' => 'available',
            ],
            [
                'key'  => 'field_creator_response_time',
                'label'=> 'زمان پاسخ‌دهی',
                'name' => 'creator_response_time',
                'type' => 'text',
                'placeholder' => 'مثال: کمتر از ۲۴ ساعت',
            ],
            [
                'key'  => 'field_creator_location',
                'label'=> 'موقعیت مکانی',
                'name' => 'creator_location',
                'type' => 'text',
                'placeholder' => 'مثال: تهران',
            ],
        ],
        'location' => [
            [['param' => 'post_type', 'operator' => '==', 'value' => 'royita_creator']],
        ],
        'menu_order' => 0,
        'position'   => 'normal',
        'style'      => 'default',
        'active'     => true,
    ]);

    // =====================================================
    // BRAND FIELD GROUP
    // =====================================================
    acf_add_local_field_group([
        'key'    => 'group_brand',
        'title'  => 'اطلاعات برند',
        'fields' => [
            [
                'key'           => 'field_brand_logo',
                'label'         => 'لوگو برند',
                'name'          => 'brand_logo',
                'type'          => 'image',
                'return_format' => 'array',
                'preview_size'  => 'thumbnail',
            ],
            [
                'key'      => 'field_brand_description',
                'label'    => 'توضیحات برند',
                'name'     => 'brand_description',
                'type'     => 'textarea',
                'rows'     => 5,
            ],
            [
                'key'  => 'field_brand_website',
                'label'=> 'وب‌سایت',
                'name' => 'brand_website',
                'type' => 'url',
            ],
            [
                'key'     => 'field_brand_industry',
                'label'   => 'صنعت',
                'name'    => 'brand_industry',
                'type'    => 'select',
                'choices' => [
                    'beauty'       => 'آرایشی و بهداشتی',
                    'electronics'  => 'الکترونیک',
                    'fashion'      => 'پوشاک و فشن',
                    'food'         => 'غذا و نوشیدنی',
                    'sports'       => 'ورزش',
                    'fintech'      => 'فین‌تک',
                    'health'       => 'سلامت',
                    'education'    => 'آموزش',
                    'travel'       => 'گردشگری',
                    'real_estate'  => 'املاک',
                ],
                'allow_null' => 0,
            ],
            [
                'key'     => 'field_brand_size',
                'label'   => 'اندازه شرکت',
                'name'    => 'brand_size',
                'type'    => 'select',
                'choices' => [
                    'startup'    => 'استارتاپ',
                    'sme'        => 'شرکت متوسط',
                    'enterprise' => 'بنگاه بزرگ',
                ],
                'default_value' => 'startup',
            ],
            [
                'key'        => 'field_brand_verified',
                'label'      => 'برند تأیید شده',
                'name'       => 'brand_verified',
                'type'       => 'true_false',
                'ui'         => 1,
                'ui_on_text' => 'بله',
                'ui_off_text'=> 'خیر',
            ],
            [
                'key'   => 'field_brand_total_campaigns',
                'label' => 'تعداد کمپین‌های منتشر شده',
                'name'  => 'brand_total_campaigns',
                'type'  => 'number',
                'min'   => 0,
                'default_value' => 0,
            ],
            [
                'key'  => 'field_brand_rating',
                'label'=> 'امتیاز برند',
                'name' => 'brand_rating',
                'type' => 'number',
                'step' => 0.1,
                'min'  => 0,
                'max'  => 5,
            ],
        ],
        'location' => [
            [['param' => 'post_type', 'operator' => '==', 'value' => 'royita_brand']],
        ],
        'active' => true,
    ]);

    // =====================================================
    // PROPOSAL FIELD GROUP
    // =====================================================
    acf_add_local_field_group([
        'key'    => 'group_proposal',
        'title'  => 'جزئیات پیشنهاد',
        'fields' => [
            [
                'key'           => 'field_proposal_campaign',
                'label'         => 'کمپین',
                'name'          => 'proposal_campaign',
                'type'          => 'post_object',
                'post_type'     => ['royita_campaign'],
                'return_format' => 'id',
                'allow_null'    => 0,
            ],
            [
                'key'           => 'field_proposal_creator',
                'label'         => 'کریتور',
                'name'          => 'proposal_creator',
                'type'          => 'post_object',
                'post_type'     => ['royita_creator'],
                'return_format' => 'id',
                'allow_null'    => 0,
            ],
            [
                'key'     => 'field_proposal_status',
                'label'   => 'وضعیت پیشنهاد',
                'name'    => 'proposal_status',
                'type'    => 'select',
                'choices' => [
                    'pending'   => 'در انتظار بررسی',
                    'accepted'  => 'پذیرفته شده',
                    'rejected'  => 'رد شده',
                    'withdrawn' => 'پس گرفته شده',
                ],
                'default_value' => 'pending',
            ],
            [
                'key'    => 'field_proposal_price',
                'label'  => 'مبلغ پیشنهادی',
                'name'   => 'proposal_price',
                'type'   => 'number',
                'prepend'=> 'تومان',
                'min'    => 0,
            ],
            [
                'key'  => 'field_proposal_delivery_days',
                'label'=> 'مدت تحویل (روز)',
                'name' => 'proposal_delivery_days',
                'type' => 'number',
                'min'  => 1,
                'append' => 'روز',
            ],
            [
                'key'      => 'field_proposal_cover_letter',
                'label'    => 'نامه پوششی',
                'name'     => 'proposal_cover_letter',
                'type'     => 'textarea',
                'rows'     => 8,
                'new_lines'=> 'wpautop',
            ],
            [
                'key'  => 'field_proposal_revisions',
                'label'=> 'تعداد ویرایش‌های مجاز',
                'name' => 'proposal_revisions',
                'type' => 'number',
                'min'  => 0,
                'max'  => 10,
                'default_value' => 2,
            ],
        ],
        'location' => [
            [['param' => 'post_type', 'operator' => '==', 'value' => 'royita_proposal']],
        ],
        'active' => true,
    ]);

    // =====================================================
    // PROJECT FIELD GROUP
    // =====================================================
    acf_add_local_field_group([
        'key'    => 'group_project',
        'title'  => 'جزئیات پروژه',
        'fields' => [
            [
                'key'           => 'field_project_campaign',
                'label'         => 'کمپین',
                'name'          => 'project_campaign',
                'type'          => 'post_object',
                'post_type'     => ['royita_campaign'],
                'return_format' => 'id',
                'allow_null'    => 0,
            ],
            [
                'key'           => 'field_project_creator',
                'label'         => 'کریتور',
                'name'          => 'project_creator',
                'type'          => 'post_object',
                'post_type'     => ['royita_creator'],
                'return_format' => 'id',
                'allow_null'    => 0,
            ],
            [
                'key'           => 'field_project_brand',
                'label'         => 'برند',
                'name'          => 'project_brand',
                'type'          => 'post_object',
                'post_type'     => ['royita_brand'],
                'return_format' => 'id',
                'allow_null'    => 1,
            ],
            [
                'key'           => 'field_project_proposal',
                'label'         => 'پیشنهاد مرتبط',
                'name'          => 'project_proposal',
                'type'          => 'post_object',
                'post_type'     => ['royita_proposal'],
                'return_format' => 'id',
                'allow_null'    => 1,
            ],
            [
                'key'     => 'field_project_status',
                'label'   => 'وضعیت پروژه',
                'name'    => 'project_status',
                'type'    => 'select',
                'choices' => [
                    'active'             => 'در حال انجام',
                    'in_review'          => 'در حال بررسی',
                    'revision_requested' => 'درخواست ویرایش',
                    'completed'          => 'تکمیل شده',
                    'disputed'           => 'مورد اختلاف',
                    'cancelled'          => 'لغو شده',
                ],
                'default_value' => 'active',
            ],
            [
                'key'  => 'field_project_price',
                'label'=> 'مبلغ پروژه',
                'name' => 'project_price',
                'type' => 'number',
                'prepend' => 'تومان',
                'min'  => 0,
            ],
            [
                'key'            => 'field_project_start_date',
                'label'          => 'تاریخ شروع',
                'name'           => 'project_start_date',
                'type'           => 'date_picker',
                'display_format' => 'Y/m/d',
                'return_format'  => 'Y/m/d',
            ],
            [
                'key'            => 'field_project_deadline',
                'label'          => 'مهلت تحویل',
                'name'           => 'project_deadline',
                'type'           => 'date_picker',
                'display_format' => 'Y/m/d',
                'return_format'  => 'Y/m/d',
            ],
            [
                'key'        => 'field_project_deliverables',
                'label'      => 'فایل‌های تحویلی',
                'name'       => 'project_deliverables',
                'type'       => 'repeater',
                'layout'     => 'block',
                'button_label' => 'افزودن فایل',
                'sub_fields' => [
                    [
                        'key'           => 'field_deliverable_file',
                        'label'         => 'فایل',
                        'name'          => 'file',
                        'type'          => 'file',
                        'return_format' => 'array',
                    ],
                    [
                        'key'   => 'field_deliverable_version',
                        'label' => 'نسخه',
                        'name'  => 'version',
                        'type'  => 'text',
                        'placeholder' => 'مثال: v1.0',
                    ],
                    [
                        'key'     => 'field_deliverable_status',
                        'label'   => 'وضعیت',
                        'name'    => 'status',
                        'type'    => 'select',
                        'choices' => [
                            'pending'  => 'در انتظار بررسی',
                            'approved' => 'تأیید شده',
                            'rejected' => 'رد شده',
                        ],
                        'default_value' => 'pending',
                    ],
                ],
            ],
            [
                'key'  => 'field_project_revisions_used',
                'label'=> 'ویرایش‌های استفاده شده',
                'name' => 'project_revisions_used',
                'type' => 'number',
                'min'  => 0,
                'default_value' => 0,
            ],
            [
                'key'  => 'field_project_revisions_max',
                'label'=> 'حداکثر ویرایش',
                'name' => 'project_revisions_max',
                'type' => 'number',
                'min'  => 0,
                'default_value' => 2,
            ],
            [
                'key'     => 'field_project_escrow_status',
                'label'   => 'وضعیت امانت‌داری',
                'name'    => 'project_escrow_status',
                'type'    => 'select',
                'choices' => [
                    'held'     => 'در امانت',
                    'released' => 'آزاد شده',
                    'refunded' => 'بازگردانده شده',
                ],
                'default_value' => 'held',
            ],
            [
                'key'  => 'field_project_payment_ref',
                'label'=> 'شناسه تراکنش',
                'name' => 'project_payment_ref',
                'type' => 'text',
            ],
        ],
        'location' => [
            [['param' => 'post_type', 'operator' => '==', 'value' => 'royita_project']],
        ],
        'active' => true,
    ]);

    // =====================================================
    // TESTIMONIAL FIELD GROUP
    // =====================================================
    acf_add_local_field_group([
        'key'    => 'group_testimonial',
        'title'  => 'جزئیات توصیه‌نامه',
        'fields' => [
            [
                'key'  => 'field_testimonial_name',
                'label'=> 'نام',
                'name' => 'testimonial_name',
                'type' => 'text',
            ],
            [
                'key'  => 'field_testimonial_role',
                'label'=> 'سمت',
                'name' => 'testimonial_role',
                'type' => 'text',
            ],
            [
                'key'  => 'field_testimonial_company',
                'label'=> 'شرکت',
                'name' => 'testimonial_company',
                'type' => 'text',
            ],
            [
                'key'           => 'field_testimonial_avatar',
                'label'         => 'تصویر',
                'name'          => 'testimonial_avatar',
                'type'          => 'image',
                'return_format' => 'array',
                'preview_size'  => 'thumbnail',
            ],
            [
                'key'      => 'field_testimonial_text',
                'label'    => 'متن توصیه‌نامه',
                'name'     => 'testimonial_text',
                'type'     => 'textarea',
                'rows'     => 5,
                'new_lines'=> 'wpautop',
            ],
            [
                'key'  => 'field_testimonial_rating',
                'label'=> 'امتیاز',
                'name' => 'testimonial_rating',
                'type' => 'number',
                'min'  => 1,
                'max'  => 5,
                'step' => 1,
                'default_value' => 5,
            ],
            [
                'key'     => 'field_testimonial_type',
                'label'   => 'نوع',
                'name'    => 'testimonial_type',
                'type'    => 'select',
                'choices' => [
                    'brand'   => 'برند',
                    'creator' => 'کریتور',
                ],
                'default_value' => 'brand',
            ],
            [
                'key'   => 'field_testimonial_order',
                'label' => 'ترتیب نمایش',
                'name'  => 'testimonial_order',
                'type'  => 'number',
                'min'   => 0,
                'default_value' => 0,
            ],
        ],
        'location' => [
            [['param' => 'post_type', 'operator' => '==', 'value' => 'royita_testimonial']],
        ],
        'active' => true,
    ]);
}
